### ISSUE TITLE
How to use Busboy (special) events

### ISSUE THREAD

**Issue by kevinprotoss** [cojs/busboy#12]
Hello,

In the doc, I did not found these relevant infos. I check the source code of this module as well. These events seems not to be registered or handled. How could I use co-busboy in Koa.js together with the limits check?

Best regards,
Kevin

**Comment by bianjp** [comment]
@kevinprotoss 
> How can Koa.js or co stuff wait for the end of such pipe? I think Koa.js will just call next middleware or response after call pipe. However, I need the result of pipe, how to make this possible?

I met the same problem. It would be nice to point out the problem and provide possible solutions in README. Would you be so kind as to make a pull request?
