### ISSUE TITLE
Deferring stream pipe

### ISSUE THREAD

**Issue by nicholaswyoung** [cojs/busboy#15]
I'm looking for a practical and performant method to defer piping of streams until I've validated other parts of the multipart request. 

Essentially, I want to limit the files that are stored (streamed to a location on disk, or to the cloud), and then pipe the matching file field streams once everything else is done. 

```javascript
//...
while (part = yield parts) {
   //... part is a stream here. 
}
//... I should have access to file streams here. 
 ```
Does anyone know how to achieve this?

**Comment by nicholaswyoung** [comment]
I came up with this, but I would love some feedback on whether this implementation is correct.

https://gist.github.com/nicholaswyoung/54a0d749ef98d9a38607

**Comment by nicholaswyoung** [comment]
@coderhaoxin @jonathanong Any ideas?

**Comment by jonathanong** [comment]
you should just use https://github.com/cojs/multipart instead. or at least look how it's implemented

**Comment by nicholaswyoung** [comment]
@jonathanong That's cool. I'm looking at it now. What happened to the ```archan``` module that it requires? That's the only thing I'm stuck on, and would like docs or usage instructions for it.

**Comment by jonathanong** [comment]
oh sorry that's pretty much deprecated because it's too complicated. i'll try to update that module soon.

until then, you can do it all sequentially. something like:

```js
while (part = yield parts) {
  yield saveTo(part, tmpfile)
}
```

**Comment by nicholaswyoung** [comment]
@jonathanong Ah, so essentially the same thing from this module. Cool. 

Is it better to handle the upload (to S3, etc.) in that loop, or is there a sane way to pipe the upload in my route handlers later on in the chain? (We're handling very large files, and buffering them to disk presents a problem. I would like to work around it if we can.)

**Comment by jonathanong** [comment]
you should do it in the same loop if you can :) that `saveTo` function could be whatever you'd like.

**Comment by nicholaswyoung** [comment]
@jonathanong So long as it returns a yieldable (Promise, Generator, Thunk) - correct?

**Comment by jonathanong** [comment]
yup, though i would recommend a promise to make it future-proof :)
