### ISSUE TITLE
it couldn't catch file stream error 

### ISSUE THREAD

**Issue by sabakugaara** [cojs/busboy#28]
when request protocol is illegal, it will emit `Part terminated early due to unexpected end of multipart data` in `node_modules/busboy/node_modules/dicer/lib/Dicer.js`

**Comment by fengmk2** [comment]
Can you show me the full stack error log?

And give me the code can reappear this bug?

**Comment by kevinprotoss** [comment]
see https://github.com/cojs/busboy/pull/29#issuecomment-164775361
