### ISSUE TITLE
co-busboy will stay stuck if you POST an empty form

### ISSUE THREAD

**Issue by cesarandreu** [cojs/busboy#9]
If you POST an empty form, it'll keep waiting and it won't respond. 

Gist with code sample and command:
https://gist.github.com/cesarandreu/9865520

**Comment by Globik** [comment]
And how to test mime type in while loop for all inputed files? for one file procces is good, but for many yieldable blocks answer to browser via ajax

**Comment by Globik** [comment]
If part.mime !='image/jpeg ......break; and now here unend loop for files among them there is one example.js, not example n.png
